-- INSERT INTO cats (name) VALUES ('Molly');
-- INSERT INTO cats (name) VALUES ('Charlie');
-- INSERT INTO cats (name, sleepy) VALUES ('Poppy', true);
-- INSERT INTO cats (name, sleepy) VALUES ('Oscar', true);
-- INSERT INTO cats (name, sleepy) VALUES ('Smudge', true);
-- INSERT INTO cats (name) VALUES ('Daisy');
